Update Github fetch call to use Auth Bearer token
bfred-it/list-github-dir-content pull request #17
Opened 2020-03-31 08:47 UTC by dan2k3k4

Fix the issue from download-directory.github.io#31 to switch from URL query parameters to Authorization HTTP header instead for the Github fetch call.

2020-03-31 11:05 UTC, fregante requested changes
If the token is missing GitHub will complain though.  The header can’t be there at all if there’s no token

2020-03-31 12:23 UTC, dan2k3k4 commented
@fregante updated, perhaps not the most elegant approach. I assume an empty header object can still be passed in?

2020-03-31 17:52 UTC, fregante commented on index.js
> +		headers: headers
I think just this

```suggestion
		headers: token ? {Authorization: `Bearer ${token}`} : undefined
```

2020-03-31 20:22 UTC, dan2k3k4 commented on index.js
> +		headers: headers
Updated 😄

2020-06-17 21:48 UTC, dan2k3k4 commented
@fregante any other changes that you'd like to see before this PR gets merged?

2020-06-18 13:16 UTC, fregante commented
Sorry for the delay! Thanks for the PR. I'll try to release this as a breaking release, but I'd like to get #16 in too first.

2020-06-18 13:17 UTC, merged